export const carsSeeds = [
  {
    propietario: 'Ramiro Salinas',
    email: 'ramirosalinas@fakemail.com',
    km: '300km',
    precio: '500000$',
    motor: '1.5T GDi (177 CV) DCT',
    generación: '2000',
    modelo: '2020',
    marca: 'Proton',
    numero_de_plazas: '5',
    numero_de_puertas: '5',
    tipo_de_carrocería: 'SUV',
    image: JSON.stringify({
      front: 'https://www.auto-data.net/images/f121/Proton-X50.jpg',
      left: 'https://www.auto-data.net/images/f113/Proton-X50.jpg',
      back: 'https://www.auto-data.net/images/f35/Proton-X50.jpg',
      inside: 'https://www.auto-data.net/images/f71/Proton-X50.jpg',
      engine: 'https://www.auto-data.net/images/f63/Proton-X50.jpg',
      right: 'https://www.auto-data.net/images/f41/Proton-X50.jpg',
    }),
  },
  {
    propietario: 'Irina Cazorla',
    email: 'irinacazorla@fakemail.com',
    km: '0km',
    precio: '5000000$',
    motor: '5.2 V10 (551 CV)',
    generación: '2009',
    modelo: 'Gallardo',
    marca: 'Lamborghini',
    numero_de_plazas: '2',
    numero_de_puertas: '2',
    tipo_de_carrocería: 'Coupe',
    image: JSON.stringify({
      front:
        'https://www.auto-data.net/images/f18/Lamborghini-Gallardo-LP-550-2.jpg',
      left: 'https://www.auto-data.net/images/f15/Lamborghini-Gallardo-LP-550-2.jpg',
      back: 'https://www.auto-data.net/images/f18/Lamborghini-Gallardo-LP-550-2_1.jpg',
      inside:
        'https://www.auto-data.net/images/f12/Lamborghini-Gallardo-LP-550-2.jpg',
      engine:
        'https://cdn.autobild.es/sites/navi.axelspringer.es/public/styles/1200/public/media/image/2017/03/622423-como-conseguir-lamborghini-gallardo-18000-euros.jpg?itok=5EnYjHgo',
      right:
        'https://www.auto-data.net/images/f4/Lamborghini-Gallardo-LP-550-2.jpg',
    }),
  },
  {
    propietario: 'Maria Esperanza Tirado',
    email: 'mariaesperanzatirado@fakemail.com',
    km: '20km',
    precio: '2000000$',
    motor: '4.7i V8 32V (450 CV)',
    generación: '2000',
    modelo: '8C Competizione',
    marca: 'Alfa Romeo',
    numero_de_plazas: '2',
    numero_de_puertas: '2',
    tipo_de_carrocería: 'Coupe',
    image: JSON.stringify({
      front:
        'https://www.auto-data.net/images/f44/Alfa-Romeo-8C-Competizione.jpg',
      left: 'https://www.auto-data.net/images/f36/Alfa-Romeo-8C-Competizione_2.jpg',
      back: 'https://www.auto-data.net/images/f36/Alfa-Romeo-8C-Competizione.jpg',
      inside:
        'https://www.autodata1.com/media/alfa-romeo/pics/alfa-romeo-8c-competizione-%5B88%5D.jpg',
      engine:
        'https://www.auto-data.net/images/f44/Alfa-Romeo-8C-Competizione.jpg',
      right:
        'https://www.auto-data.net/images/f76/Alfa-Romeo-8C-Competizione.jpg',
    }),
  },
  {
    propietario: 'Vera Espinoza',
    email: 'veraespinoza@fakemail.com',
    km: '6000km',
    precio: '365000$',
    motor: 'P85D PERFORMANCE (691 CV) AWD',
    generación: '2016',
    modelo: 'Model S',
    marca: 'Tesla',
    numero_de_plazas: '5',
    numero_de_puertas: '5',
    tipo_de_carrocería: 'Liftback',
    image: JSON.stringify({
      front: 'https://www.auto-data.net/images/f68/Tesla-Model-S.jpg',
      left: 'https://www.auto-data.net/images/f42/Tesla-Model-S.jpg',
      back: 'https://www.auto-data.net/images/f30/file8139016.jpg',
      inside: 'https://www.auto-data.net/images/f0/file3193979.jpg',
      engine: 'https://www.auto-data.net/images/f17/file8410675.jpg',
      right: 'https://www.auto-data.net/images/f42/Tesla-Model-S_2.jpg',
    }),
  },
  {
    propietario: 'Encarnacion Pacheco',
    email: 'encarnacionpacheco@fakemail.com',
    km: '2000km',
    precio: '540124$',
    motor: '4.4 V8 (600 CV) xDrive Steptronic',
    generación: '2019',
    modelo: 'M8',
    marca: 'BMW',
    numero_de_plazas: '5',
    numero_de_puertas: '4',
    tipo_de_carrocería: 'Coupe',
    image: JSON.stringify({
      front: 'https://www.auto-data.net/images/f76/BMW-M8-Gran-Coupe-F93.jpg',
      left: 'https://www.auto-data.net/images/f93/BMW-M8-Gran-Coupe-F93.jpg',
      back: 'auto-data.net/images/f87/BMW-M8-Gran-Coupe-F93.jpg',
      inside: 'https://www.auto-data.net/images/f31/BMW-M8-Gran-Coupe-F93.jpg',
      engine: 'https://www.auto-data.net/images/f33/BMW-M8-Gran-Coupe-F93.jpg',
      right: 'https://www.auto-data.net/images/f102/BMW-M8-Gran-Coupe-F93.jpg',
    }),
  },
]
