PUT http://localhost:3000/api/cars/1
Content-Type: application/json

{
  "general": 0,
  "documentacion_y_mantenimiento": 5,
  "ruedas__frenos__suspension_y_direccion": 5,
  "carroceria": 0,
  "motor": 0,
  "alumbrado": 0,
  "volante_y_tablero": 2,
  "interior_y_asientos": 2,
  "interior_general": 0
}