export const DEVELOPMENTMODE = 'development'
export const TEST = 'TEST'
export const BASE_URL_API = '/api/'
export const PATH_INICIAL = '/'
export const PARAM_PATH_ID = '/:id'
export const STATIC_PUBLIC_PATH = './dist'
export const CARS = 'cars'
export const GENERALS = 'generals'
