POST http://localhost:3000/api/car
Content-Type: application/json

{
  "propietario": "'DROP TABLE car",
  "email": 0,
  "km": 0,
  "precio": 0,
  "motor": "V8",
  "generación": 2000,
  "modelo": "modelo",
  "marca": "marca",
  "numero_de_plazas": 4,
  "numero_de_puertas": 4,
  "tipo_de_carrocería": "tipo de carrocería",
  "image": {
    "front": "",
    "back": "",
    "left": "",
    "right": "",
    "inside": "",
    "outside": "",
    "engine": ""
  }
}