POST http://localhost:3000/api/car
Content-Type: application/json

{
  "propietario": "'DROP TABLE car",
  "email": 0,
  "km": 0,
  "precio": 0,
  "image": {
    "front": "",
    "back": "",
    "left": "",
    "right": "",
    "inside": "",
    "outside": "",
    "engine": ""
  }
}