PUT http://localhost:3000/api/car/1
Content-Type: application/json

{
  "propietario": "aaa",
  "email": 0,
  "km": 0,
  "precio": 0,
  "image": {
    "front": "aaaa",
    "back": "",
    "left": "",
    "right": "",
    "inside": "",
    "outside": "",
    "engine": ""
  }
}